language: python

env:
  DATABASE_URL="dbname='ireporter' host='127.0.0.1' port='5432' user='postgres' password=''"
  DATABASE_TEST_URL="dbname='ireporter' host='127.0.0.1' port='5432' user='postgres' password=''"
  APP_SETTINGS="testing"
  SECRET_KEY="mcogol"

python:
  - "2.7"

install:
  - pip install -r requirements.txt
  - pip install coveralls codecov

services:
  - postgresql
addons:
  postgresql: "9.6"

before_script:
  - psql -c 'CREATE DATABASE ireporter' -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public to postgres ;" -U postgres

script:
  - nosetests --with-coverage --cover-package=app app/tests

after_success:
  - coveralls
  - codecov --token=1ddf61d6-2791-4420-902c-a2bd31e17c4b
